name: Test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`
      - name: Validate Packer template
        run: packer validate -var-file="variables.auto.pkvars.hcl" .

  build-ami:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`
      - name: Zip all files
        run: zip -r webapp.zip .
      - name: Run Packer
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: packer build -var-file="variables.auto.pkvars.hcl" .
